---
apiVersion: v1
kind: Service
metadata:
  name: memproxy
  labels:
    app: memproxy
spec:
  ports:
  - port: 80
    name: web
  type: ClusterIP
  selector:
    app: memproxy
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: memproxy
  labels:
    app: memproxy
spec:
  selector:
    matchLabels:
      app: memproxy
  template:
    metadata:
      labels:
        app: memproxy
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: memproxy
        image: docker.io/zorkinaa/memproxy:0.1.0
        args:
        - "--backend=memcached"
        - "--listen=8080"
        - "--origin=origin-web-server:80"    # pod hostName
        - "--cache-address=localhost:11211"  # shared localhost
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: memcached
        image: memcached
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30


